### ISSUE TITLE
Different hashes generated for a vite bundled file with the same filename.

### ISSUE THREAD

**Issue by joepagan** [ElMassimo/vite-plugin-manifest-sri#2]
Hey, Thanks for your work on this plugin but found an issue unless I'm doing something wrong?

Between deployments no changes were applied to a file: `@commons/searchBarImportWrapper.js`
The file is imported in several vite entry points the app uses.
As the filename suggests, a dynamic import will occur inside of it
The resulting file is bundled as `searchBarImportWrapper.7ca027a1.js` over 2 deployments, however, a different integrity hash was generated on different deployments which as you'd imagine... the following occurred:

- JS file with same filename saves in the browser’s file cache has a specific hash
- deployment happens
- SRI plugin generates a new “integrity” (hash) of the JS file (even though it hasn’t changed) with the same filename
- browser tries to load file from cache because filename is identical
- browser blocks file from loading because hash integrity does not match the integrity on the server

This was particularly difficult to identify because naturally my primary browser for dev work is chrome with the "disable cache" checkbox checked in dev tools:

<img width="221" alt="image" src="https://user-images.githubusercontent.com/2337910/213038886-c943070d-71da-4975-8311-491e8fa3621e.png">

I could not replicated it until I tried the same website I had visited months before in a different chrome profile, where hammering refresh yielded the same error:

![image](https://user-images.githubusercontent.com/2337910/213039514-050845c3-6b7a-4d9a-aaba-031768fcf80b.png)

Do you have any suggestions on what this could be or how to overcome it?

**Comment by ElMassimo** [comment]
Hi Joe!

The [hashing function](https://github.com/ElMassimo/vite-plugin-manifest-sri/blob/main/src/index.ts#L68) is deterministic, if the content of the file is the same, it should generate the same hash.

At the same time, Rollup is also using a deterministic hash function, and the filename should change if the content changes.

Any ideas on how to replicate the behavior you have observed in this application?

**Comment by ElMassimo** [comment]
Rollup 3 has fixed many issues related to fingerprinting files, so upgrading to Vite 4 should avoid this type of problem.

If you still replicate it and are able to provide a minimal reproduction, I can take a look.
