### ISSUE TITLE
the generated manifest.json is not a valid json

### ISSUE THREAD

**Issue by duongphuhiep** [ElMassimo/vite-plugin-manifest-sri#4]
From time to time, I got 2 more closing '}'

![image](https://user-images.githubusercontent.com/1638594/230756986-76c8aa1a-f874-44ff-890e-43d41d45c5bf.png)

this is my `vite.config.ts`

```ts
import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { resolve } from 'path';
import manifestSRI from 'vite-plugin-manifest-sri';

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [svelte(), manifestSRI()],
    resolve: {
        alias: {
            '@shared': resolve(__dirname, '../shared'),
            '@sdk': resolve(__dirname, 'src/sdk'),
        },
    },
    build: {
        manifest: true,
        lib: {
            entry: resolve(__dirname, 'src/sdk/main.ts'),
            name: 'LwHostedFields',
            fileName: `${process.env.npm_package_name}`,
            formats: ['es','iife'],
        },
        watch: {}
    },
});
```

Note that: I use `vite build` in watch mode to regenerate the manifest for each changes. Most of time, it happen only on the first run, if I regenerate the manifest again (or re-run `vite build` again, everything become normal..

**Comment by ElMassimo** [comment]
Hi Duong!

This library is using [JSON.stringify](https://github.com/ElMassimo/vite-plugin-manifest-sri/blob/main/src/index.ts#L59), which should never generate invalid JSON.

In addition, the default write mode in Node.js will replace the file content.

It's likely that the write that is making the file invalid is happening in a different Vite plugin (or in Vite itself).

If you provide a minimal reproduction without other plugins I can take a look.
